/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public class gp_environment {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gp_environment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gp_environment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libclientJNI.delete_gp_environment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setApi_id(int value) {
    libclientJNI.gp_environment_api_id_set(swigCPtr, this, value);
  }

  public int getApi_id() {
    return libclientJNI.gp_environment_api_id_get(swigCPtr, this);
  }

  public void setLayer(int value) {
    libclientJNI.gp_environment_layer_set(swigCPtr, this, value);
  }

  public int getLayer() {
    return libclientJNI.gp_environment_layer_get(swigCPtr, this);
  }

  public void setDisable_updates(int value) {
    libclientJNI.gp_environment_disable_updates_set(swigCPtr, this, value);
  }

  public int getDisable_updates() {
    return libclientJNI.gp_environment_disable_updates_get(swigCPtr, this);
  }

  public void setEncryption_password(String value) {
    libclientJNI.gp_environment_encryption_password_set(swigCPtr, this, value);
  }

  public String getEncryption_password() {
    return libclientJNI.gp_environment_encryption_password_get(swigCPtr, this);
  }

  public void setDevice_model(String value) {
    libclientJNI.gp_environment_device_model_set(swigCPtr, this, value);
  }

  public String getDevice_model() {
    return libclientJNI.gp_environment_device_model_get(swigCPtr, this);
  }

  public void setSystem_version(String value) {
    libclientJNI.gp_environment_system_version_set(swigCPtr, this, value);
  }

  public String getSystem_version() {
    return libclientJNI.gp_environment_system_version_get(swigCPtr, this);
  }

  public void setApp_version(String value) {
    libclientJNI.gp_environment_app_version_set(swigCPtr, this, value);
  }

  public String getApp_version() {
    return libclientJNI.gp_environment_app_version_get(swigCPtr, this);
  }

  public void setLang_code(String value) {
    libclientJNI.gp_environment_lang_code_set(swigCPtr, this, value);
  }

  public String getLang_code() {
    return libclientJNI.gp_environment_lang_code_get(swigCPtr, this);
  }

  public void setDocuments_folder(String value) {
    libclientJNI.gp_environment_documents_folder_set(swigCPtr, this, value);
  }

  public String getDocuments_folder() {
    return libclientJNI.gp_environment_documents_folder_get(swigCPtr, this);
  }

  public void setSupported_types_count(int value) {
    libclientJNI.gp_environment_supported_types_count_set(swigCPtr, this, value);
  }

  public int getSupported_types_count() {
    return libclientJNI.gp_environment_supported_types_count_get(swigCPtr, this);
  }

  public void setSupported_types(SWIGTYPE_p_long_long value) {
    libclientJNI.gp_environment_supported_types_set(swigCPtr, this, SWIGTYPE_p_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_long_long getSupported_types() {
    long cPtr = libclientJNI.gp_environment_supported_types_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long_long(cPtr, false);
  }

  public gp_environment() {
    this(libclientJNI.new_gp_environment(), true);
  }

}
