/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public final class gp_event {
  public final static gp_event RESPONSE = new gp_event("RESPONSE", libclientJNI.RESPONSE_get());
  public final static gp_event UPDATE = new gp_event("UPDATE", libclientJNI.UPDATE_get());
  public final static gp_event PROTO_STATE = new gp_event("PROTO_STATE", libclientJNI.PROTO_STATE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static gp_event swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + gp_event.class + " with value " + swigValue);
  }

  private gp_event(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private gp_event(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private gp_event(String swigName, gp_event swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static gp_event[] swigValues = { RESPONSE, UPDATE, PROTO_STATE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

