/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public class gp_rx_event {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gp_rx_event(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gp_rx_event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libclientJNI.delete_gp_rx_event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(gp_event value) {
    libclientJNI.gp_rx_event_type_set(swigCPtr, this, value.swigValue());
  }

  public gp_event getType() {
    return gp_event.swigToEnum(libclientJNI.gp_rx_event_type_get(swigCPtr, this));
  }

  public void setData(gp_rx_data value) {
    libclientJNI.gp_rx_event_data_set(swigCPtr, this, gp_rx_data.getCPtr(value), value);
  }

  public gp_rx_data getData() {
    long cPtr = libclientJNI.gp_rx_event_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gp_rx_data(cPtr, false);
  }

  public void setDate(long value) {
    libclientJNI.gp_rx_event_date_set(swigCPtr, this, value);
  }

  public long getDate() {
    return libclientJNI.gp_rx_event_date_get(swigCPtr, this);
  }

  public void setState(gp_connection_state value) {
    libclientJNI.gp_rx_event_state_set(swigCPtr, this, value.swigValue());
  }

  public gp_connection_state getState() {
    return gp_connection_state.swigToEnum(libclientJNI.gp_rx_event_state_get(swigCPtr, this));
  }

  public gp_rx_event() {
    this(libclientJNI.new_gp_rx_event(), true);
  }

}
