/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public class libclient {
  public static SWIGTYPE_p_int new_intArray(int nelements) {
    long cPtr = libclientJNI.new_intArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intArray(SWIGTYPE_p_int ary) {
    libclientJNI.delete_intArray(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int intArray_getitem(SWIGTYPE_p_int ary, int index) {
    return libclientJNI.intArray_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
  }

  public static void intArray_setitem(SWIGTYPE_p_int ary, int index, int value) {
    libclientJNI.intArray_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_long new_longArray(int nelements) {
    long cPtr = libclientJNI.new_longArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
  }

  public static void delete_longArray(SWIGTYPE_p_long ary) {
    libclientJNI.delete_longArray(SWIGTYPE_p_long.getCPtr(ary));
  }

  public static int longArray_getitem(SWIGTYPE_p_long ary, int index) {
    return libclientJNI.longArray_getitem(SWIGTYPE_p_long.getCPtr(ary), index);
  }

  public static void longArray_setitem(SWIGTYPE_p_long ary, int index, int value) {
    libclientJNI.longArray_setitem(SWIGTYPE_p_long.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_unsigned_int new_unsigendIntArray(int nelements) {
    long cPtr = libclientJNI.new_unsigendIntArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public static void delete_unsigendIntArray(SWIGTYPE_p_unsigned_int ary) {
    libclientJNI.delete_unsigendIntArray(SWIGTYPE_p_unsigned_int.getCPtr(ary));
  }

  public static long unsigendIntArray_getitem(SWIGTYPE_p_unsigned_int ary, int index) {
    return libclientJNI.unsigendIntArray_getitem(SWIGTYPE_p_unsigned_int.getCPtr(ary), index);
  }

  public static void unsigendIntArray_setitem(SWIGTYPE_p_unsigned_int ary, int index, long value) {
    libclientJNI.unsigendIntArray_setitem(SWIGTYPE_p_unsigned_int.getCPtr(ary), index, value);
  }

  public static int gp_client_create(gp_environment environment) {
    return libclientJNI.gp_client_create(gp_environment.getCPtr(environment), environment);
  }

  public static void gp_destroy(int client) {
    libclientJNI.gp_destroy(client);
  }

  public static int gp_client_send(int client, gp_tx_data request) {
    return libclientJNI.gp_client_send(client, gp_tx_data.getCPtr(request), request);
  }

  public static gp_rx_event gp_client_receive(int client, double timeout) {
    long cPtr = libclientJNI.gp_client_receive(client, timeout);
    return (cPtr == 0) ? null : new gp_rx_event(cPtr, false);
  }

  public static void gp_client_pause(int client) {
    libclientJNI.gp_client_pause(client);
  }

  public static void gp_client_resume(int client) {
    libclientJNI.gp_client_resume(client);
  }

  public static void gp_client_stop(int client) {
    libclientJNI.gp_client_stop(client);
  }

  public static void gp_client_reset_credentials(int client) {
    libclientJNI.gp_client_reset_credentials(client);
  }

  public static double gp_client_get_global_time(int client) {
    return libclientJNI.gp_client_get_global_time(client);
  }

  public static void gp_client_cancel_request(int client, int id) {
    libclientJNI.gp_client_cancel_request(client, id);
  }

  public static void gp_client_set_log_level(int level) {
    libclientJNI.gp_client_set_log_level(level);
  }

}
