/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "gp/proto/gp_client_data.h"
#include "gp/proto/gp_client.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_RESPONSE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum gp_event result;
  
  (void)jenv;
  (void)jcls;
  result = (enum gp_event)RESPONSE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_UPDATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum gp_event result;
  
  (void)jenv;
  (void)jcls;
  result = (enum gp_event)UPDATE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_PROTO_1STATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum gp_event result;
  
  (void)jenv;
  (void)jcls;
  result = (enum gp_event)PROTO_STATE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_CONNECTING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum gp_connection_state result;
  
  (void)jenv;
  (void)jcls;
  result = (enum gp_connection_state)CONNECTING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_CONNECTED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum gp_connection_state result;
  
  (void)jenv;
  (void)jcls;
  result = (enum gp_connection_state)CONNECTED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1error_1code_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  gp_error *arg1 = (gp_error *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(gp_error **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->code = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1error_1code_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  gp_error *arg1 = (gp_error *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(gp_error **)&jarg1; 
  result = (int) ((arg1)->code);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1error_1desc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  gp_error *arg1 = (gp_error *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(gp_error **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->desc);
    if (arg2) {
      arg1->desc = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->desc, (const char *)arg2);
    } else {
      arg1->desc = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gp_libclient_libclientJNI_gp_1error_1desc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  gp_error *arg1 = (gp_error *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(gp_error **)&jarg1; 
  result = (char *) ((arg1)->desc);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_new_1gp_1error(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  gp_error *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (gp_error *)calloc(1, sizeof(gp_error));
  *(gp_error **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_delete_1gp_1error(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gp_error *arg1 = (gp_error *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gp_error **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1data_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct gp_data *arg1 = (struct gp_data *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_data **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1data_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_data *arg1 = (struct gp_data *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_data **)&jarg1; 
  result =  ((arg1)->length);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1data_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct gp_data *arg1 = (struct gp_data *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_data **)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  if (arg1) (arg1)->value = (unsigned char const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1data_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_data *arg1 = (struct gp_data *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_data **)&jarg1; 
  result = (unsigned char *) ((arg1)->value);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_new_1gp_1data(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct gp_data *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct gp_data *)calloc(1, sizeof(struct gp_data));
  *(struct gp_data **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_delete_1gp_1data(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct gp_data *arg1 = (struct gp_data *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct gp_data **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1data_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gp_rx_data *arg1 = (struct gp_rx_data *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_data **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1data_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_rx_data *arg1 = (struct gp_rx_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_data **)&jarg1; 
  result = (int) ((arg1)->id);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1data_1error_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct gp_rx_data *arg1 = (struct gp_rx_data *) 0 ;
  gp_error *arg2 = (gp_error *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct gp_rx_data **)&jarg1; 
  arg2 = *(gp_error **)&jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1data_1error_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_rx_data *arg1 = (struct gp_rx_data *) 0 ;
  gp_error *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_data **)&jarg1; 
  result = (gp_error *) ((arg1)->error);
  *(gp_error **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1data_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct gp_rx_data *arg1 = (struct gp_rx_data *) 0 ;
  struct gp_data *arg2 = (struct gp_data *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct gp_rx_data **)&jarg1; 
  arg2 = *(struct gp_data **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1data_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_rx_data *arg1 = (struct gp_rx_data *) 0 ;
  struct gp_data *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_data **)&jarg1; 
  result = (struct gp_data *) ((arg1)->data);
  *(struct gp_data **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_new_1gp_1rx_1data(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct gp_rx_data *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct gp_rx_data *)calloc(1, sizeof(struct gp_rx_data));
  *(struct gp_rx_data **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_delete_1gp_1rx_1data(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct gp_rx_data *arg1 = (struct gp_rx_data *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct gp_rx_data **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  enum gp_event arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  arg2 = (enum gp_event)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  enum gp_event result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  result = (enum gp_event) ((arg1)->type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  struct gp_rx_data *arg2 = (struct gp_rx_data *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  arg2 = *(struct gp_rx_data **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  struct gp_rx_data *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  result = (struct gp_rx_data *) ((arg1)->data);
  *(struct gp_rx_data **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1date_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->date = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1date_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  result = (unsigned int) ((arg1)->date);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1state_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  enum gp_connection_state arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  arg2 = (enum gp_connection_state)jarg2; 
  if (arg1) (arg1)->state = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1rx_1event_1state_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  enum gp_connection_state result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  result = (enum gp_connection_state) ((arg1)->state);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_new_1gp_1rx_1event(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct gp_rx_event *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct gp_rx_event *)calloc(1, sizeof(struct gp_rx_event));
  *(struct gp_rx_event **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_delete_1gp_1rx_1event(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct gp_rx_event *arg1 = (struct gp_rx_event *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct gp_rx_event **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1tx_1data_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct gp_tx_data *arg1 = (struct gp_tx_data *) 0 ;
  struct gp_data *arg2 = (struct gp_data *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct gp_tx_data **)&jarg1; 
  arg2 = *(struct gp_data **)&jarg2; 
  if (arg1) (arg1)->data = (struct gp_data const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1tx_1data_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_tx_data *arg1 = (struct gp_tx_data *) 0 ;
  struct gp_data *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_tx_data **)&jarg1; 
  result = (struct gp_data *) ((arg1)->data);
  *(struct gp_data **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_new_1gp_1tx_1data(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct gp_tx_data *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct gp_tx_data *)calloc(1, sizeof(struct gp_tx_data));
  *(struct gp_tx_data **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_delete_1gp_1tx_1data(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct gp_tx_data *arg1 = (struct gp_tx_data *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct gp_tx_data **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1api_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->api_id = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1api_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (int) ((arg1)->api_id);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1layer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->layer = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1layer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (int) ((arg1)->layer);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1disable_1updates_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->disable_updates = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1disable_1updates_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (int) ((arg1)->disable_updates);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1encryption_1password_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->encryption_password);
    if (arg2) {
      arg1->encryption_password = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->encryption_password, (const char *)arg2);
    } else {
      arg1->encryption_password = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1encryption_1password_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (char *) ((arg1)->encryption_password);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1device_1model_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->device_model);
    if (arg2) {
      arg1->device_model = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->device_model, (const char *)arg2);
    } else {
      arg1->device_model = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1device_1model_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (char *) ((arg1)->device_model);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1system_1version_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->system_version);
    if (arg2) {
      arg1->system_version = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->system_version, (const char *)arg2);
    } else {
      arg1->system_version = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1system_1version_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (char *) ((arg1)->system_version);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1app_1version_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->app_version);
    if (arg2) {
      arg1->app_version = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->app_version, (const char *)arg2);
    } else {
      arg1->app_version = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1app_1version_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (char *) ((arg1)->app_version);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1lang_1code_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->lang_code);
    if (arg2) {
      arg1->lang_code = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->lang_code, (const char *)arg2);
    } else {
      arg1->lang_code = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1lang_1code_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (char *) ((arg1)->lang_code);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1documents_1folder_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->documents_folder);
    if (arg2) {
      arg1->documents_folder = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->documents_folder, (const char *)arg2);
    } else {
      arg1->documents_folder = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1documents_1folder_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (char *) ((arg1)->documents_folder);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1supported_1types_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->supported_types_count = arg2;
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1supported_1types_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (int) ((arg1)->supported_types_count);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1supported_1types_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  arg2 = *(unsigned int **)&jarg2; 
  if (arg1) (arg1)->supported_types = arg2;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1environment_1supported_1types_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  unsigned int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (unsigned int *) ((arg1)->supported_types);
  *(unsigned int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_new_1gp_1environment(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct gp_environment *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct gp_environment *)calloc(1, sizeof(struct gp_environment));
  *(struct gp_environment **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_delete_1gp_1environment(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct gp_environment **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1create(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gp_environment *arg1 = (struct gp_environment *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gp_environment **)&jarg1; 
  result = (int)gp_client_create(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1destroy(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  gp_destroy(arg1);
}


SWIGEXPORT jint JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1send(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  int arg1 ;
  struct gp_tx_data *arg2 = (struct gp_tx_data *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = (int)jarg1; 
  arg2 = *(struct gp_tx_data **)&jarg2; 
  result = (int)gp_client_send(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1receive(JNIEnv *jenv, jclass jcls, jint jarg1, jdouble jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  double arg2 ;
  struct gp_rx_event *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (double)jarg2; 
  result = (struct gp_rx_event *)gp_client_receive(arg1,arg2);
  *(struct gp_rx_event **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1pause(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  gp_client_pause(arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1resume(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  gp_client_resume(arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1stop(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  gp_client_stop(arg1);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1reset_1credentials(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  gp_client_reset_credentials(arg1);
}


SWIGEXPORT jdouble JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1get_1global_1time(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jdouble jresult = 0 ;
  int arg1 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (double)gp_client_get_global_time(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1cancel_1request(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  int arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  gp_client_cancel_request(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_org_gp_libclient_libclientJNI_gp_1client_1set_1log_1level(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  gp_client_set_log_level(arg1);
}


#ifdef __cplusplus
}
#endif

