/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public final class gp_connection_state {
  public final static gp_connection_state CONNECTING = new gp_connection_state("CONNECTING", libclientJNI.CONNECTING_get());
  public final static gp_connection_state CONNECTED = new gp_connection_state("CONNECTED", libclientJNI.CONNECTED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static gp_connection_state swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + gp_connection_state.class + " with value " + swigValue);
  }

  private gp_connection_state(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private gp_connection_state(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private gp_connection_state(String swigName, gp_connection_state swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static gp_connection_state[] swigValues = { CONNECTING, CONNECTED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

