/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public class gp_error {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gp_error(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gp_error obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libclientJNI.delete_gp_error(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCode(int value) {
    libclientJNI.gp_error_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return libclientJNI.gp_error_code_get(swigCPtr, this);
  }

  public void setDesc(String value) {
    libclientJNI.gp_error_desc_set(swigCPtr, this, value);
  }

  public String getDesc() {
    return libclientJNI.gp_error_desc_get(swigCPtr, this);
  }

  public gp_error() {
    this(libclientJNI.new_gp_error(), true);
  }

}
