/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public class gp_tx_data {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gp_tx_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gp_tx_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libclientJNI.delete_gp_tx_data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(gp_data value) {
    libclientJNI.gp_tx_data_data_set(swigCPtr, this, gp_data.getCPtr(value), value);
  }

  public gp_data getData() {
    long cPtr = libclientJNI.gp_tx_data_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new gp_data(cPtr, false);
  }

  public gp_tx_data() {
    this(libclientJNI.new_gp_tx_data(), true);
  }

}
