/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public class libclient {
  public static int gp_client_create(gp_environment environment) {
    return libclientJNI.gp_client_create(gp_environment.getCPtr(environment), environment);
  }

  public static void gp_destroy(int client) {
    libclientJNI.gp_destroy(client);
  }

  public static int gp_client_send(int client, gp_tx_data request) {
    return libclientJNI.gp_client_send(client, gp_tx_data.getCPtr(request), request);
  }

  public static gp_rx_event gp_client_receive(int client, double timeout) {
    long cPtr = libclientJNI.gp_client_receive(client, timeout);
    return (cPtr == 0) ? null : new gp_rx_event(cPtr, false);
  }

  public static void gp_client_pause(int client) {
    libclientJNI.gp_client_pause(client);
  }

  public static void gp_client_resume(int client) {
    libclientJNI.gp_client_resume(client);
  }

  public static void gp_client_stop(int client) {
    libclientJNI.gp_client_stop(client);
  }

  public static void gp_client_reset_credentials(int client) {
    libclientJNI.gp_client_reset_credentials(client);
  }

  public static double gp_client_get_global_time(int client) {
    return libclientJNI.gp_client_get_global_time(client);
  }

  public static void gp_client_cancel_request(int client, int id) {
    libclientJNI.gp_client_cancel_request(client, id);
  }

}
