/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gp.libclient;

public class libclientJNI {
  public final static native int RESPONSE_get();
  public final static native int UPDATE_get();
  public final static native int PROTO_STATE_get();
  public final static native int CONNECTING_get();
  public final static native int CONNECTED_get();
  public final static native void gp_error_code_set(long jarg1, gp_error jarg1_, int jarg2);
  public final static native int gp_error_code_get(long jarg1, gp_error jarg1_);
  public final static native void gp_error_desc_set(long jarg1, gp_error jarg1_, String jarg2);
  public final static native String gp_error_desc_get(long jarg1, gp_error jarg1_);
  public final static native long new_gp_error();
  public final static native void delete_gp_error(long jarg1);
  public final static native void gp_data_length_set(long jarg1, gp_data jarg1_, long jarg2);
  public final static native long gp_data_length_get(long jarg1, gp_data jarg1_);
  public final static native void gp_data_value_set(long jarg1, gp_data jarg1_, long jarg2);
  public final static native long gp_data_value_get(long jarg1, gp_data jarg1_);
  public final static native long new_gp_data();
  public final static native void delete_gp_data(long jarg1);
  public final static native void gp_rx_data_id_set(long jarg1, gp_rx_data jarg1_, int jarg2);
  public final static native int gp_rx_data_id_get(long jarg1, gp_rx_data jarg1_);
  public final static native void gp_rx_data_error_set(long jarg1, gp_rx_data jarg1_, long jarg2, gp_error jarg2_);
  public final static native long gp_rx_data_error_get(long jarg1, gp_rx_data jarg1_);
  public final static native void gp_rx_data_data_set(long jarg1, gp_rx_data jarg1_, long jarg2, gp_data jarg2_);
  public final static native long gp_rx_data_data_get(long jarg1, gp_rx_data jarg1_);
  public final static native long new_gp_rx_data();
  public final static native void delete_gp_rx_data(long jarg1);
  public final static native void gp_rx_event_type_set(long jarg1, gp_rx_event jarg1_, int jarg2);
  public final static native int gp_rx_event_type_get(long jarg1, gp_rx_event jarg1_);
  public final static native void gp_rx_event_data_set(long jarg1, gp_rx_event jarg1_, long jarg2, gp_rx_data jarg2_);
  public final static native long gp_rx_event_data_get(long jarg1, gp_rx_event jarg1_);
  public final static native void gp_rx_event_date_set(long jarg1, gp_rx_event jarg1_, long jarg2);
  public final static native long gp_rx_event_date_get(long jarg1, gp_rx_event jarg1_);
  public final static native void gp_rx_event_state_set(long jarg1, gp_rx_event jarg1_, int jarg2);
  public final static native int gp_rx_event_state_get(long jarg1, gp_rx_event jarg1_);
  public final static native long new_gp_rx_event();
  public final static native void delete_gp_rx_event(long jarg1);
  public final static native void gp_tx_data_data_set(long jarg1, gp_tx_data jarg1_, long jarg2, gp_data jarg2_);
  public final static native long gp_tx_data_data_get(long jarg1, gp_tx_data jarg1_);
  public final static native long new_gp_tx_data();
  public final static native void delete_gp_tx_data(long jarg1);
  public final static native void gp_environment_api_id_set(long jarg1, gp_environment jarg1_, int jarg2);
  public final static native int gp_environment_api_id_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_layer_set(long jarg1, gp_environment jarg1_, int jarg2);
  public final static native int gp_environment_layer_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_disable_updates_set(long jarg1, gp_environment jarg1_, int jarg2);
  public final static native int gp_environment_disable_updates_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_encryption_password_set(long jarg1, gp_environment jarg1_, String jarg2);
  public final static native String gp_environment_encryption_password_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_device_model_set(long jarg1, gp_environment jarg1_, String jarg2);
  public final static native String gp_environment_device_model_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_system_version_set(long jarg1, gp_environment jarg1_, String jarg2);
  public final static native String gp_environment_system_version_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_app_version_set(long jarg1, gp_environment jarg1_, String jarg2);
  public final static native String gp_environment_app_version_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_lang_code_set(long jarg1, gp_environment jarg1_, String jarg2);
  public final static native String gp_environment_lang_code_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_documents_folder_set(long jarg1, gp_environment jarg1_, String jarg2);
  public final static native String gp_environment_documents_folder_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_supported_types_count_set(long jarg1, gp_environment jarg1_, int jarg2);
  public final static native int gp_environment_supported_types_count_get(long jarg1, gp_environment jarg1_);
  public final static native void gp_environment_supported_types_set(long jarg1, gp_environment jarg1_, long jarg2);
  public final static native long gp_environment_supported_types_get(long jarg1, gp_environment jarg1_);
  public final static native long new_gp_environment();
  public final static native void delete_gp_environment(long jarg1);
  public final static native int gp_client_create(long jarg1, gp_environment jarg1_);
  public final static native void gp_destroy(int jarg1);
  public final static native int gp_client_send(int jarg1, long jarg2, gp_tx_data jarg2_);
  public final static native long gp_client_receive(int jarg1, double jarg2);
  public final static native void gp_client_pause(int jarg1);
  public final static native void gp_client_resume(int jarg1);
  public final static native void gp_client_stop(int jarg1);
  public final static native void gp_client_reset_credentials(int jarg1);
  public final static native double gp_client_get_global_time(int jarg1);
  public final static native void gp_client_cancel_request(int jarg1, int jarg2);
}
